language: php

sudo: false
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: 7.4
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
    - php: nightly
      env: COMPOSER_FLAGS="--ignore-platform-reqs"
  allow_failures:
    - php: nightly

before_install:
  # Set up Composer
  - composer self-update || true
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install:
  - composer install --no-interaction $COMPOSER_FLAGS

script:
  - ./vendor/bin/phpunit
  - ./vendor/bin/ecs check src

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Cache vendor dirs
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
    - cs_cache
