language: php

sudo: false
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.3 # PHP CS Fixer does not support it yet
    - php: nightly

before_script:
  # Set up Composer
  - composer self-update || true
  - composer install --no-interaction

script:
  # PHPUnit
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  # PHP CodeSniffer
  - vendor/bin/phpcs -p --report=summary
  # PHP CS Fixer
  - vendor/bin/php-cs-fixer fix --cache-file cs_cache/php_cs_fixer --dry-run

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Cache vendor dirs
cache:
  directories:
    - vendor
    - $COMPOSER_CACHE_DIR
    - cs_cache
